var Adoption1 = artifacts.require("ERC20.sol");
var Adoption2 = artifacts.require("PowerfulERC20.sol");
var Adoption3 = artifacts.require("SafeMath.sol");
var Adoption4 = artifacts.require("ServicePayerMock.sol");
var Adoption5 = artifacts.require("ServiceReceiver.sol");
var Adoption6 = artifacts.require("SimpleERC20.sol");
var Adoption7 = artifacts.require("StandardERC20.sol");
var Adoption8 = artifacts.require("TokenRecover.sol");
var Adoption9 = artifacts.require("Address.sol");
var Adoption10 = artifacts.require("CommonERC20.sol");
var Adoption11 = artifacts.require("Context.sol");
var Adoption12 = artifacts.require("ERC1363.sol");
var Adoption13 = artifacts.require("ERC1363ReceiverMock.sol");
var Adoption14 = artifacts.require("ERC1363SpenderMock.sol");
var Adoption15 = artifacts.require("ERC165.sol");
var Adoption16 = artifacts.require("ERC165Checker.sol");
var Adoption17 = artifacts.require("ERC20Capped.sol");
var Adoption18 = artifacts.require("ERC20Mock.sol");
//var Adoption19 = artifacts.require("GenratorCopyright.sol");
var Adoption20 = artifacts.require("IERC1363.sol");
var Adoption21 = artifacts.require("IERC1363Receiver.sol");
var Adoption22 = artifacts.require("IERC1363Spender.sol");
var Adoption23 = artifacts.require("IERC165.sol");
var Adoption24 = artifacts.require("Ownable.sol");
//var Adoption25 = artifacts.require("PowerfulERC20.sol");
//var Adoption26 = artifacts.require("ServicePayer.sol");
//var Adoption27 = artifacts.require("IERC1363.sol");

module.exports = function(deployer) {
  deployer.deploy(Adoption1);
  deployer.deploy(Adoption2);
  deployer.deploy(Adoption3);
  deployer.deploy(Adoption4);
  deployer.deploy(Adoption5);
  deployer.deploy(Adoption6);
  deployer.deploy(Adoption7);
  deployer.deploy(Adoption8);
  deployer.deploy(Adoption9);
  deployer.deploy(Adoption10);
  deployer.deploy(Adoption11);
  deployer.deploy(Adoption12);
  deployer.deploy(Adoption13);
  deployer.deploy(Adoption14);
  deployer.deploy(Adoption15);
  deployer.deploy(Adoption16);
  deployer.deploy(Adoption17);
  deployer.deploy(Adoption18);
 // deployer.deploy(Adoption19);
  deployer.deploy(Adoption20);
  deployer.deploy(Adoption21);
  deployer.deploy(Adoption22);
  deployer.deploy(Adoption23);
  deployer.deploy(Adoption24);
  //deployer.deploy(Adoption25);
  //deployer.deploy(Adoption26);
  //deployer.deploy(Adoption27);
 
};
